services:
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["celery", "-A", "court.jobs.celery:celery_app", "worker", "--beat", "--loglevel=info"]
    volumes:
      - fantasy_court_data:/data
    environment:
      - DATA_ROOT=/data
      - RL_DEBUG=0
      - TZ=America/Los_Angeles
    env_file:
      - prod.env
    container_name: fantasy-court-celery
    restart: unless-stopped

volumes:
  fantasy_court_data:
    driver: local
