services:
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["celery", "-A", "court.jobs.celery:celery_app", "worker", "--beat", "--loglevel=info"]
    volumes:
      - fantasy_court_data:/data
    environment:
      - DATA_ROOT=/data
      - RL_DEBUG=0
      - TZ=America/Los_Angeles
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - prod.env
    container_name: fantasy-court-celery
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - fantasy_court_redis_data:/data
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    container_name: fantasy-court-redis


volumes:
  fantasy_court_data:
    driver: local
  fantasy_court_redis_data:
    driver: local
