// This file is auto-generated by @hey-api/openapi-ts

import type { CreateTaskResponse, ListTasksResponse, ReadTaskResponse, UpdateTaskResponse } from './types.gen';

const taskListItemSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

const paginatedBaseTaskListItemSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return taskListItemSchemaResponseTransformer(item);
    });
    return data;
};

export const listTasksResponseTransformer = async (data: any): Promise<ListTasksResponse> => {
    data = paginatedBaseTaskListItemSchemaResponseTransformer(data);
    return data;
};

const taskReadSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const createTaskResponseTransformer = async (data: any): Promise<CreateTaskResponse> => {
    data = taskReadSchemaResponseTransformer(data);
    return data;
};

export const readTaskResponseTransformer = async (data: any): Promise<ReadTaskResponse> => {
    data = taskReadSchemaResponseTransformer(data);
    return data;
};

export const updateTaskResponseTransformer = async (data: any): Promise<UpdateTaskResponse> => {
    data = taskReadSchemaResponseTransformer(data);
    return data;
};
