"""Update citation schema

Revision ID: 0cba6b67d43f
Revises: ed8022bc7e8e
Create Date: 2025-10-19 00:25:48.944794

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cba6b67d43f"
down_revision: str | None = "ed8022bc7e8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_citations", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_citations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###
