"""add unlisted cases

Revision ID: 12690f7e5864
Revises: 3d5ec1f28d66
Create Date: 2026-09-22 12:10:09.872242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12690f7e5864"
down_revision: str | None = "3d5ec1f28d66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fantasy_court_cases",
        sa.Column("unlisted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "fantasy_court_cases", sa.Column("record_text", sa.String(), nullable=True)
    )
    op.add_column(
        "fantasy_court_cases",
        sa.Column("exhibit_paths", sa.ARRAY(sa.String()), nullable=True),
    )
    op.alter_column(
        "fantasy_court_cases", "episode_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "fantasy_court_cases", "segment_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "fantasy_court_cases",
        "start_time_s",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fantasy_court_cases",
        "end_time_s",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fantasy_court_cases",
        "end_time_s",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fantasy_court_cases",
        "start_time_s",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fantasy_court_cases", "segment_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "fantasy_court_cases", "episode_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("fantasy_court_cases", "exhibit_paths")
    op.drop_column("fantasy_court_cases", "record_text")
    op.drop_column("fantasy_court_cases", "unlisted")
    # ### end Alembic commands ###
