"""Add bucket path to episode

Revision ID: 177b39a4992e
Revises: d350340c5d0b
Create Date: 2025-10-17 22:34:15.353978

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "177b39a4992e"
down_revision: str | None = "d350340c5d0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "podcast_episodes", sa.Column("bucket_mp3_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("podcast_episodes", "bucket_mp3_path")
    # ### end Alembic commands ###
