"""Add provenance IDs

Revision ID: 17a6a81ff881
Revises: 13146c8ea2ea
Create Date: 2025-10-17 22:57:34.572423

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17a6a81ff881"
down_revision: str | None = "13146c8ea2ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode_transcripts", sa.Column("provenance_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "episode_transcripts", "provenances", ["provenance_id"], ["id"]
    )
    op.add_column(
        "fantasy_court_segments",
        sa.Column("provenance_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None, "fantasy_court_segments", "provenances", ["provenance_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fantasy_court_segments", type_="foreignkey")
    op.drop_column("fantasy_court_segments", "provenance_id")
    op.drop_constraint(None, "episode_transcripts", type_="foreignkey")
    op.drop_column("episode_transcripts", "provenance_id")
    # ### end Alembic commands ###
