"""Add segment_id to transcript table

Revision ID: 17e2a9977bf0
Revises: c52d23471643
Create Date: 2025-10-17 23:44:53.765479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17e2a9977bf0"
down_revision: str | None = "c52d23471643"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode_transcripts", sa.Column("segment_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "episode_transcripts", "fantasy_court_segments", ["segment_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "episode_transcripts", type_="foreignkey")
    op.drop_column("episode_transcripts", "segment_id")
    # ### end Alembic commands ###
