"""Add found_no_segments and found_no_cases flags

Revision ID: 3d5ec1f28d66
Revises: b9b3cea18905
Create Date: 2025-10-19 19:29:53.043841

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d5ec1f28d66"
down_revision: str | None = "b9b3cea18905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fantasy_court_segments",
        sa.Column(
            "found_no_cases", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "podcast_episodes",
        sa.Column(
            "found_no_segments", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###

    # Initialize flags for existing records that have no segments/cases
    # Set found_no_segments=true for episodes that don't have a segment
    op.execute("""
        UPDATE podcast_episodes
        SET found_no_segments = true
        WHERE id NOT IN (
            SELECT episode_id FROM fantasy_court_segments
        )
    """)

    # Set found_no_cases=true for segments that don't have any cases
    op.execute("""
        UPDATE fantasy_court_segments
        SET found_no_cases = true
        WHERE id NOT IN (
            SELECT segment_id FROM fantasy_court_cases
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("podcast_episodes", "found_no_segments")
    op.drop_column("fantasy_court_segments", "found_no_cases")
    # ### end Alembic commands ###
