"""Add episodes table

Revision ID: 4d67d738cfa6
Revises: a78cae674fca
Create Date: 2025-10-17 22:22:31.502185

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d67d738cfa6"
down_revision: str | None = "a78cae674fca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "podcast_episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("description_html", sa.String(), nullable=True),
        sa.Column("pub_date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("canonical_mp3_url", sa.String(), nullable=True),
        sa.Column("rss_feed_url", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_podcast_episodes_created_at"),
        "podcast_episodes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_podcast_episodes_guid"), "podcast_episodes", ["guid"], unique=False
    )
    op.create_index(
        op.f("ix_podcast_episodes_pub_date"),
        "podcast_episodes",
        ["pub_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_podcast_episodes_title"), "podcast_episodes", ["title"], unique=False
    )
    op.drop_index("ix_tasks_created_at", table_name="tasks")
    op.drop_index("ix_tasks_updated_at", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "completed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("priority", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="tasks_pkey"),
    )
    op.create_index("ix_tasks_updated_at", "tasks", ["updated_at"], unique=False)
    op.create_index("ix_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.drop_index(op.f("ix_podcast_episodes_title"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_pub_date"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_guid"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_created_at"), table_name="podcast_episodes")
    op.drop_table("podcast_episodes")
    # ### end Alembic commands ###
