"""Add start_time_s/end_time_s to transcript

Revision ID: 515f0f781c94
Revises: 17e2a9977bf0
Create Date: 2025-10-18 14:27:06.837545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "515f0f781c94"
down_revision: str | None = "17e2a9977bf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column(
        "episode_transcripts", sa.Column("start_time_s", sa.Float(), nullable=True)
    )
    op.add_column(
        "episode_transcripts", sa.Column("end_time_s", sa.Float(), nullable=True)
    )

    # Populate from JSON for existing rows
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE episode_transcripts
            SET start_time_s = (transcript_json->>'start_time_s')::float,
                end_time_s = (transcript_json->>'end_time_s')::float
            WHERE transcript_json ? 'start_time_s'
              AND transcript_json ? 'end_time_s'
        """)
    )

    # Make columns non-nullable
    op.alter_column("episode_transcripts", "start_time_s", nullable=False)
    op.alter_column("episode_transcripts", "end_time_s", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episode_transcripts", "end_time_s")
    op.drop_column("episode_transcripts", "start_time_s")
    # ### end Alembic commands ###
