"""Flesh out case and opinion schema

Revision ID: 98bbba79762f
Revises: 515f0f781c94
Create Date: 2025-10-18 15:26:13.849180

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98bbba79762f"
down_revision: str | None = "515f0f781c94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fantasy_court_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.Column("docket_number", sa.String(), nullable=False),
        sa.Column("start_time_s", sa.Float(), nullable=False),
        sa.Column("end_time_s", sa.Float(), nullable=False),
        sa.Column("fact_summary", sa.String(), nullable=False),
        sa.Column("case_caption", sa.String(), nullable=True),
        sa.Column("questions_presented_html", sa.String(), nullable=True),
        sa.Column("procedural_posture", sa.String(), nullable=True),
        sa.Column("case_topics", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["podcast_episodes.id"]),
        sa.ForeignKeyConstraint(["provenance_id"], ["provenances.id"]),
        sa.ForeignKeyConstraint(["segment_id"], ["fantasy_court_segments.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fantasy_court_cases_created_at"),
        "fantasy_court_cases",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fantasy_court_cases_docket_number"),
        "fantasy_court_cases",
        ["docket_number"],
        unique=True,
    )
    op.create_table(
        "case_citations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("citing_case_id", sa.Integer(), nullable=False),
        sa.Column("cited_case_id", sa.Integer(), nullable=False),
        sa.Column("citation_context", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cited_case_id"], ["fantasy_court_cases.id"]),
        sa.ForeignKeyConstraint(["citing_case_id"], ["fantasy_court_cases.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_citations_cited_case_id"),
        "case_citations",
        ["cited_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_citing_case_id"),
        "case_citations",
        ["citing_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_created_at"),
        "case_citations",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "fantasy_court_opinions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.Column("authorship_html", sa.String(), nullable=False),
        sa.Column("opinion_body_html", sa.String(), nullable=False),
        sa.Column("holding_statement_html", sa.String(), nullable=False),
        sa.Column("reasoning_summary_html", sa.String(), nullable=False),
        sa.Column("pdf_path", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["fantasy_court_cases.id"]),
        sa.ForeignKeyConstraint(["provenance_id"], ["provenances.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fantasy_court_opinions_created_at"),
        "fantasy_court_opinions",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fantasy_court_opinions_created_at"),
        table_name="fantasy_court_opinions",
    )
    op.drop_table("fantasy_court_opinions")
    op.drop_index(op.f("ix_case_citations_created_at"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_citing_case_id"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_cited_case_id"), table_name="case_citations")
    op.drop_table("case_citations")
    op.drop_index(
        op.f("ix_fantasy_court_cases_docket_number"), table_name="fantasy_court_cases"
    )
    op.drop_index(
        op.f("ix_fantasy_court_cases_created_at"), table_name="fantasy_court_cases"
    )
    op.drop_table("fantasy_court_cases")
    # ### end Alembic commands ###
