"""Recreate citation table

Revision ID: b9b3cea18905
Revises: d26ee02839bb
Create Date: 2025-10-19 00:26:59.080666

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9b3cea18905"
down_revision: str | None = "d26ee02839bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_citations",
        sa.Column("citing_case_id", sa.Integer(), nullable=False),
        sa.Column("cited_case_id", sa.Integer(), nullable=False),
        sa.Column("citation_context", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cited_case_id"], ["fantasy_court_cases.id"]),
        sa.ForeignKeyConstraint(["citing_case_id"], ["fantasy_court_cases.id"]),
        sa.PrimaryKeyConstraint("citing_case_id", "cited_case_id"),
    )
    op.create_index(
        op.f("ix_case_citations_cited_case_id"),
        "case_citations",
        ["cited_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_citing_case_id"),
        "case_citations",
        ["citing_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_created_at"),
        "case_citations",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_citations_created_at"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_citing_case_id"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_cited_case_id"), table_name="case_citations")
    op.drop_table("case_citations")
    # ### end Alembic commands ###
