"""Revise col names

Revision ID: c89b05afe0e8
Revises: 17a6a81ff881
Create Date: 2025-10-17 23:05:14.640384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c89b05afe0e8"
down_revision: str | None = "17a6a81ff881"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fantasy_court_segments", sa.Column("start_time_s", sa.Float(), nullable=False)
    )
    op.add_column(
        "fantasy_court_segments", sa.Column("end_time_s", sa.Float(), nullable=False)
    )
    op.drop_column("fantasy_court_segments", "end_time")
    op.drop_column("fantasy_court_segments", "start_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fantasy_court_segments",
        sa.Column(
            "start_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "fantasy_court_segments",
        sa.Column(
            "end_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("fantasy_court_segments", "end_time_s")
    op.drop_column("fantasy_court_segments", "start_time_s")
    # ### end Alembic commands ###
