"""Remove citation table

Revision ID: d26ee02839bb
Revises: 0cba6b67d43f
Create Date: 2025-10-19 00:26:28.072085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d26ee02839bb"
down_revision: str | None = "0cba6b67d43f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_citations_cited_case_id"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_citing_case_id"), table_name="case_citations")
    op.drop_index(op.f("ix_case_citations_created_at"), table_name="case_citations")
    op.drop_table("case_citations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_citations",
        sa.Column("citing_case_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cited_case_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("citation_context", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cited_case_id"],
            ["fantasy_court_cases.id"],
            name=op.f("case_citations_cited_case_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["citing_case_id"],
            ["fantasy_court_cases.id"],
            name=op.f("case_citations_citing_case_id_fkey"),
        ),
    )
    op.create_index(
        op.f("ix_case_citations_created_at"),
        "case_citations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_citing_case_id"),
        "case_citations",
        ["citing_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_citations_cited_case_id"),
        "case_citations",
        ["cited_case_id"],
        unique=False,
    )
    # ### end Alembic commands ###
