"""Add uniqueness to guid

Revision ID: d350340c5d0b
Revises: 4d67d738cfa6
Create Date: 2025-10-17 22:25:27.386144

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d350340c5d0b"
down_revision: str | None = "4d67d738cfa6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_podcast_episodes_guid", table_name="podcast_episodes")
    op.create_index(
        op.f("ix_podcast_episodes_guid"), "podcast_episodes", ["guid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_podcast_episodes_guid"), table_name="podcast_episodes")
    op.create_index(
        "ix_podcast_episodes_guid", "podcast_episodes", ["guid"], unique=False
    )
    # ### end Alembic commands ###
