"""Add agent_message_log to fantasy_court_opinions

Revision ID: ed8022bc7e8e
Revises: 98bbba79762f
Create Date: 2025-10-18 22:34:05.068263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed8022bc7e8e"
down_revision: str | None = "98bbba79762f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fantasy_court_opinions",
        sa.Column(
            "agent_message_log", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fantasy_court_opinions", "agent_message_log")
    # ### end Alembic commands ###
